### ISSUE TITLE
Creating wallet and saving the keystore.

### ISSUE THREAD

**Issue by BogdanMaier** [BitProfile/Xeth#41]
Hello,

I installed xeth, and created a wallet. It has been syncing for a while then I restarted my pc and,  only startup image is displaying the UI does not load and  I did not created a backup for my keystore. And my etherium coins arrieved. How can I create a back up of the store and fix my xeth installation?

**Comment by devktor** [comment]
Hey, 

You can still do the backup even without UIX. Please tell me what operating system do you have and what xeth version have you installed.

**Comment by BogdanMaier** [comment]
Windows 10,  latest stable version.

**Comment by devktor** [comment]
Please check C:\Users\\\*USERNAME\*\AppData\Roaming\Ethereum\keystore  (use your windows username instead of \*USERNAME\*) . There you'll find all your keys. You should copy them to a safe location.


Also please try to rename C:\\Users\\\*USERNAME\*\\.parity directory, maybe blockchain got corrupted when you restarted, this should help to re-start xeth. Meanwhile we are working on a fix that will help to eliminate this kind of problems, thank you for reporting it.

**Comment by BogdanMaier** [comment]
Awsome! Thanks! One more question if my blockchain is indeed corrupted (36.4 GB (39,120,205,077 bytes)) can I somehow fix it? (Do I necessarily need to synch the blockchain)?

**Comment by devktor** [comment]
You can't easily do it with this version. We are working on a auto-diagnostic/auto-fix feature. At the moment easiest way is to just flush the entire blockchain.
